[server]
maxUploadSize = 500
enableXsrfProtection = true

[theme]
primaryColor = "#00377B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7FB"
textColor = "#1F2937"
font = "sans serif"

[browser]
gatherUsageStats = false
